### ISSUE TITLE
问题报告 在ios上的问题

### ISSUE THREAD

**Issue by Wei-Winter** [zyronon/V2Next#100]
1、是否在关闭其他插件和脚本后复现？

已经关闭除脚本管理器以外的所有扩展，脚本也只有一个

2、描述
我在iPhone上使用，调不出脚本的菜单设置，点击菜单没有任何反应。并且上下滑动网页浏览器工具栏本应该隐藏，安装脚本后滑动网页都不能隐藏浏览器的工具栏。尝试过Orion➕暴力猴，还有Safari➕Stay，这两种浏览器和脚本管理器在ios上存在同样的问题。都是不能调出菜单还有不能够隐藏工具栏

3、帖子ID
在这里填写帖子ID

4、截图

**Comment by zyronon** [comment]
收到

**Comment by aidenlx** [comment]
tampermonkey iOS测试后，只能在请求桌面网站时使用，默认移动端时无法生效

**Comment by zyronon** [comment]
pc 脚本在手机上不生效的，有判断。

App 已发布， 可以试试。

不想装 App 可以试试这个脚本，之前专门为移动端网页做的。但移动端脚本以后不会维护了

https://greasyfork.org/zh-CN/scripts/485356-v2next-mobile
