### ISSUE TITLE
问题报告

### ISSUE THREAD

**Issue by tjx0722** [zyronon/V2Next#101]
1、是否在关闭其他插件和脚本后复现？

是的

2、描述

点击“个人中心”，下拉查看“XXX创建的更多主题”，然后随便点一个进去都无法查看。但是浏览器标签页名称已经改变了，具体可以看截图

3、帖子ID

1049767

4、截图

![image](https://github.com/zyronon/web-scripts/assets/42849881/2800178a-6929-47ae-844e-5a0fb9c4c1d9)

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
已在10.3版本修复，请更新
