### ISSUE TITLE
问题报告（主题弹框显示功能失效）

### ISSUE THREAD

**Issue by xiejinpeng007** [zyronon/V2Next#102]
1、是否在关闭其他插件和脚本后复现？

是

2、描述

使用插件很长时间了（超过一年），最近几个月主题弹框显示功能失效，会直接打开新的帖子，其它功能正常。
尝试过重装，关闭其它所有插件等方法都没办法解决。

系统版本：MacOS 13.2   Chrome 125   v2未登录状态

3、帖子ID
所有帖子

4、截图

可以直接按Ctrl + V 复制在这里（复制成功后会显示一串地址）

**Comment by zyronon** [comment]
未登录情况下是有这个bug，目前比较忙，暂时没时间修复

登录后是可以正常使用的

**Comment by zyronon** [comment]
已在10.3版本修复，请更新
