### ISSUE TITLE
浏览器右侧滚动条样式被修改

### ISSUE THREAD

**Issue by yakun4566** [zyronon/V2Next#104]
1、是否在关闭其他插件和脚本后复现？

复现

2、描述
在开启脚本后，浏览器右侧滚动条样式被修改，且没有上下按钮

3、帖子ID
v站主页列表

4、截图
开启插件后截图
![image](https://github.com/zyronon/web-scripts/assets/18443998/3343188b-8134-4470-874f-bcf6cc8d4e52)
关闭插件后截图
![image](https://github.com/zyronon/web-scripts/assets/18443998/3c7c62cc-59c5-4487-a2da-07c1e9b33ae1)

**Comment by zyronon** [comment]
是的，脚本把滚动条改了

**Comment by leic4u** [comment]
Chrome 默认的滚动条太难看了，本脚本做了一定优化，但是自定义程度不足。

可以考虑用 stylus 装个 Global Overlay Scrollbar 样式，可以强制用 Fluent Overlay Scrollbar 覆盖所有网站的滚动条样式，包括本脚本的滚动条，还可以调整粗细、颜色，非常好用。

**Comment by jinggqu** [comment]
不敢苟同现在的Scrollbar样式，实在是过于太显眼，能给个选项直接使用默认样式吗？ @leic4u

**Comment by leic4u** [comment]
![PixPin_2024-07-16_14-28-39](https://github.com/user-attachments/assets/e8b36e11-7a10-4934-89d1-77a01981e04a)

用 stylus 装个 Global Overlay Scrollbar 样式。

**Comment by jinggqu** [comment]
单独另外安装一个全局生效的插件来解决脚本带来的问题，我觉得这不是一个很好的办法。

反之，不对 Scrollbar 做任何特殊处理应该是默认行为，对 Scrollbar 样式有特殊需求的用户才应该安装上述插件来自定义其样式。
