### ISSUE TITLE
脚本介绍的 Netlify 托管站点（ v2next.netlify.app ）挂了

### ISSUE THREAD

**Issue by leic4u** [zyronon/V2Next#105]
![Clip_2024-06-26_16-04-20](https://github.com/zyronon/web-scripts/assets/32786903/f0af684b-2176-4db3-8282-0ef2f7498631)

**Comment by zyronon** [comment]
不想搞了，挂了就挂了吧，反正也没人用

**Comment by leic4u** [comment]
> 不想搞了，挂了就挂了吧，反正也没人用

但是你脚本的 icon 是引用的这个地址，要不传到 github 来，用 github 的地址吧。
https://github.com/zyronon/web-scripts/blob/d56f70a9fdc2acea6bbceceed0a7b6f3a4580f58/V2Next.user.js#L8 
https://github.com/zyronon/web-scripts/blob/d56f70a9fdc2acea6bbceceed0a7b6f3a4580f58/V2Next-Mobile.user.js#L8

**Comment by zyronon** [comment]
谢谢，看到你提的pr了。

我现在把脚本介绍项目托管到vercel了，https://v2ex-script.vercel.app/

icon的引用地址也改了

**Comment by leic4u** [comment]
不客气哈，还得感谢你写了这么好用的脚本。😋
