### ISSUE TITLE
问题报告：WOW 分区的样式问题

### ISSUE THREAD

**Issue by AemonCao** [zyronon/V2Next#108]
1、是否在关闭其他插件和脚本后复现？

若是冲突问题，issue将被搁置

2、描述

WOW分区的样式会有问题。

3、帖子ID

https://www.v2ex.com/go/wow

4、截图

![image](https://github.com/zyronon/web-scripts/assets/19542659/2185d0e7-e7d1-4926-b1e6-614afc5a5e8a)

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
近期修复

**Comment by zyronon** [comment]
已修复
