### ISSUE TITLE
问题报告 添加标签的弹窗优先级低于帖子内容弹窗导致被遮盖

### ISSUE THREAD

**Issue by iulo** [zyronon/V2Next#110]
1、是否在关闭其他插件和脚本后复现？

若是冲突问题，issue将被搁置

2、描述

首页点击打开帖子详情（弹窗形式），给某人点击添加标签，标签弹窗会在帖子弹窗下面，无法使用

3、帖子ID
任意

4、截图
看了下，帖子的post-detail的z-index:1002， 标签的tag-modal的z-index:1001，应该这里的问题

**Comment by zyronon** [comment]
已修复，需要手动更新下

https://greasyfork.org/zh-CN/scripts/458024
