### ISSUE TITLE
宽度较大的代码块导致帖子本体无法正常显示

### ISSUE THREAD

**Issue by chesha1** [zyronon/V2Next#111]
案例：https://www.v2ex.com/t/1062089?p=1

显示效果：
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/37c43f4c-37a3-4b9b-a89e-9e08df51bdbd">

**Comment by chesha1** [comment]
Any updates？

**Comment by zyronon** [comment]
> Any updates？

近期修复

**Comment by zyronon** [comment]
已修复
