### ISSUE TITLE
功能请求: 更换cdn

### ISSUE THREAD

**Issue by itning** [zyronon/V2Next#112]
1、描述
现在的cdn使用的https证书是wotrus(沃通)的。
希望能替换为其他家的cdn，例如：
```
// @require      https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
// @require      https://cdn.jsdelivr.net/npm/vue@3.4.14/dist/vue.runtime.global.prod.js
```
  
2、这个功能解决了什么问题？
有一些的用户沃通证书是手动黑名单的

**Comment by zyronon** [comment]
ok



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月17日 23:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zyronon/web-scripts] 功能请求: 更换cdn (Issue #112) |

1、描述
现在的cdn使用的https证书是wotrus(沃通)的。
希望能替换为其他家的cdn，例如：

// @require      ***@***.***/dist/jquery.min.js
// @require      ***@***.***/dist/vue.runtime.global.prod.js


2、这个功能解决了什么问题？
有一些的用户沃通证书是手动黑名单的

**Comment by zyronon** [comment]
已更改
