### ISSUE TITLE
问题报告 点进个人主页，不显示主题帖

### ISSUE THREAD

**Issue by psklf** [zyronon/V2Next#115]
1、是否在关闭其他插件和脚本后复现？

若是冲突问题，issue将被搁置

2、描述

点进某个用户的个人主页看不到他发的主题帖。

3、帖子ID
在这里填写帖子ID
NA

4、截图

![Screenshot 2024-08-29 at 11-14-03 V2EX › yuntun](https://github.com/user-attachments/assets/ae352787-157d-48cd-9ac6-8a3299f07fe2)

环境：

MacOS Firefox 129.0.2 (64-bit)

**Comment by zyronon** [comment]
我这边测试是正常的，麻烦提供下id

**Comment by zyronon** [comment]
的确有问题，已复制。近期会修复

**Comment by zyronon** [comment]
已修复
