### ISSUE TITLE
功能请求：能不能尽量不要修改原有样式？

### ISSUE THREAD

**Issue by starryspace** [zyronon/V2Next#116]
1、描述
能不能尽量不要修改原有样式？

2、这个功能解决了什么问题？

原站样式比较简洁，现在作了不少修改，没有原来简洁、清晰了。使用这个脚本主要是需要楼中楼功能。

#### 帖子页面

* ~~回帖内容文字左侧缩进位置~~
原版文字左侧没有竖线，并且与用户名左对齐；新版有竖线、没有左对齐，看着不整齐清晰。如果竖线是为了楼中楼功能增加的，那第一层也没必要使用竖线吧。
**2024年10月27日备注**：使用楼中楼后，横向需要更大的空间，左边不对齐也有合理性，可以不改；竖线也有折叠功能，也可以不改。

* 回帖用户图标大小
原版较小，新版变大。
* 回帖内容文字字体大小
原版较小，新版变大了，如果在设置里调小一号，又太小了。原来的尺寸就挺合适的。
**2024年10月27日备注**：图标和字体大小问题，在使用一段时间后，倒也习惯了更大的图标和字体，看着也挺舒心。这两个问题可以不改，或者在设置中增加个选项可以将字体、图标调整为原有大小，作者您自己看着办吧。

![IMG_20240830_143211](https://github.com/user-attachments/assets/3d922e5c-3f4e-4a90-b79b-b0ce091ecd80)

#### 帖子列表页面

* 帖子标题文字左侧缩进位置
帖子标题没有与上方的元素左对齐，看着不整齐。建议，如果脚本设置中“列表展示方式”为“表格”，则不要调整缩进位置。
* 帖子节点与用户名的位置
原版节点在前、用户名在后，新版调换了位置。建议，这个不要调整。

![IMG_20240830_144434](https://github.com/user-attachments/assets/92facd6c-8c70-41e6-91d3-779eba01de03)

**Comment by zyronon** [comment]
好的，近期会修复

**Comment by starryspace** [comment]
> 好的，近期会修复

感谢楼主的劳动。
发帖的时候，这个脚本只用了几天，对脚本全部功能不太熟悉。现在用了几个月了，觉得挺好用的，有一些不同的想法，为了方便查看，更新在主帖中。我主要使用楼中楼功能，这个功能很好用，虽然修改了原有样式，总体上还是方便了这么多。

**Comment by jinggqu** [comment]
以前也有 issue（#104）提到了尽量不要修改原有样式，但作者似乎不在乎。

使用这个脚本主要是为了楼中楼功能，还请作者不要改变大家长久以来的使用习惯，不要强加自己的审美于所有人。

即使想要修改原有样式，我认为也可以提供一个恢复的选项，而不是默认更改。感谢。

**Comment by zyronon** [comment]
@jinggqu 

104 这个问题这个已经改了，现在把滚动条恢复了。

不是不在乎，有兴趣可以看看 https://github.com/zyronon/V2Next/discussions/7

和已经关闭的issue。基本是有问必答，有求必应，网友提的绝大多数问题和要求，我都尽量满足了。

问题是，这个脚本日活2000，https://greasyfork.org/zh-CN/scripts/458024-v2ex-next-v2next/stats
。我在站内几乎很少看到有人帮我宣传，我有时候发贴说更新了新功能，让帮我点个star，也没人点star

**Comment by jinggqu** [comment]
@zyronon 理解理解，非常感谢你的辛勤劳动。

这个脚本的大部分用户可能都是潜水党，平时都只是看帖不发帖不回帖，确实可能存在没人帮忙宣传的情况，下次发帖我给你点赞。😆

不过个人认为现在的功能已经很完备了，大家的需求可以按照自己的精力选择性做，不要太为难自己了。目前这个脚本能完美满足我的使用需求，再次感谢！

**Comment by zyronon** [comment]
App 已发布， @jinggqu @starryspace 两位可以试试。

@starryspace 移动端脚本以后不会维护了
