### ISSUE TITLE
Base64 解码不用每次都出现。

### ISSUE THREAD

**Issue by mistkafka** [zyronon/V2Next#118]
1、描述
当选择的文本带有  连续base64字符，结尾为等号 的时候，才显示 base64 解码。
  
2、这个功能解决了什么问题？
现在选中的文本带个英文单词，都会显示 base64 解码的 tooltip，其实挺烦的。

**Comment by zyronon** [comment]
只有选中的字符中包含英文才会显示 tooltip



在 2024-09-13 09:57:32，"行之" ***@***.***> 写道：

1、描述
当选择的文本带有 base64 特征的时候，才显示 base64 解码。

2、这个功能解决了什么问题？
现在无论是不是 base64 文本，都会显示 base64 解码的 tooltip，其实挺烦的。

**Comment by mistkafka** [comment]
好吧～ 也不是那么重要。
