### ISSUE TITLE
“点击列表的帖子，打开详情弹框”功能失效

### ISSUE THREAD

**Issue by DYS7516461** [zyronon/V2Next#12]
脚本开启“点击列表的帖子，打开详情弹框”，chrome开启“内存节省程序”，当打开一个帖子时，即该帖子详情会以弹窗形式打开，此时去使用其他标签页，过一段时间，该标签页会被“内存节省程序”回收内存，重新回到V站标签页，此时会自动刷新该页面，弹窗效果会消失，该问题可以通过以下方法重现：弹窗打开的时候，直接点击chrome浏览器刷新按钮，会重现该问题

**Comment by zyronon** [comment]
无解....
