### ISSUE TITLE
功能请求 请问一下这个base64解码能不能加上一个加密的功能呢？

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [zyronon/V2Next#120]
1、描述
请尽可能详细描述您需要的特性。
加上一个base64加密的功能。  

2、这个功能解决了什么问题？
请尽可能详尽地说明这个需求的用例和场景
不知道为啥，我在Google搜索的那些base64解码的在线网站，把我的邮箱加密后发到V2，然后用这个解码出来的邮箱是不正确的，我试了好几个在线网站都是这样的。加密出来的码是一样的。
freevpnvrys@gmail.com

**Comment by zyronon** [comment]
我测试了没问题啊

我在这个网站  https://tool.chinaz.com/tools/base64.aspx 加密了你的邮箱，ZnJlZXZwbnZyeXNAZ21haWwuY29t

然后在回复到了v2的帖子 https://www.v2ex.com/t/1078049#reply10 里面，用脚本的解密功能，正确还原了邮箱
