### ISSUE TITLE
问题报告:10.14版本无法加载楼中楼

### ISSUE THREAD

**Issue by wk333** [zyronon/V2Next#122]
> 1、是否在关闭其他插件和脚本后复现？
> 
> 是
> 
> 2、描述
> 
> 楼中楼显示失败
> 
> https://greasyfork.org/zh-CN/scripts/458024-v2ex-next-v2next
> 
> 3、帖子ID 
https://www.v2ex.com/t/1080307#reply38
> 
> 4、截图 ![image](https://private-user-images.githubusercontent.com/30464860/376482580-fea64661-824a-4db2-8596-838ae6a2a5e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3ODYsIm5iZiI6MTcyODk3MzQ4NiwicGF0aCI6Ii8zMDQ2NDg2MC8zNzY0ODI1ODAtZmVhNjQ2NjEtODI0YS00ZGIyLTg1OTYtODM4YWU2YTJhNWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjhmMzQ1ODVlODE2ZmU1YzJlNjg3ZTA5Y2RjODA1NTRjZTEwODkzODg4ZGRiMWJiNzk2NGIxNTdmMjE5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sM5_4PEeinSFbyD-T6rsELx5uoJuFxUgNX2WJfgm9VU) ![image](https://private-user-images.githubusercontent.com/30464860/376482854-c8c19541-0217-4ab3-ae03-66e00d1f5134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3ODYsIm5iZiI6MTcyODk3MzQ4NiwicGF0aCI6Ii8zMDQ2NDg2MC8zNzY0ODI4NTQtYzhjMTk1NDEtMDIxNy00YWIzLWFlMDMtNjZlMDBkMWY1MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDVlYTYzMjgyMmU3ZTljMjkyYzU4M2YzYzI5ZDk1OWNkYmY2OGI0ZmNiZGE4NTI5Njc4OWQyNWY4MTExYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0VOplRx86Uw-9kUqzOFytWLRkSn343y9ZPzsgQg6dnE)
> 
> 可以直接按Ctrl + V 复制在这里（复制成功后会显示一串地址）

**Comment by wk333** [comment]
> 1、是否在关闭其他插件和脚本后复现？
> 
> 是
> 
> 2、描述
> 
> 楼中楼显示失败
> 
> https://greasyfork.org/zh-CN/scripts/458024-v2ex-next-v2next
> 
> 3、帖子ID 
https://www.v2ex.com/t/1080307#reply38
> 
> 4、截图 ![image](https://private-user-images.githubusercontent.com/30464860/376482580-fea64661-824a-4db2-8596-838ae6a2a5e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3ODYsIm5iZiI6MTcyODk3MzQ4NiwicGF0aCI6Ii8zMDQ2NDg2MC8zNzY0ODI1ODAtZmVhNjQ2NjEtODI0YS00ZGIyLTg1OTYtODM4YWU2YTJhNWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjhmMzQ1ODVlODE2ZmU1YzJlNjg3ZTA5Y2RjODA1NTRjZTEwODkzODg4ZGRiMWJiNzk2NGIxNTdmMjE5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sM5_4PEeinSFbyD-T6rsELx5uoJuFxUgNX2WJfgm9VU) ![image](https://private-user-images.githubusercontent.com/30464860/376482854-c8c19541-0217-4ab3-ae03-66e00d1f5134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3ODYsIm5iZiI6MTcyODk3MzQ4NiwicGF0aCI6Ii8zMDQ2NDg2MC8zNzY0ODI4NTQtYzhjMTk1NDEtMDIxNy00YWIzLWFlMDMtNjZlMDBkMWY1MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDVlYTYzMjgyMmU3ZTljMjkyYzU4M2YzYzI5ZDk1OWNkYmY2OGI0ZmNiZGE4NTI5Njc4OWQyNWY4MTExYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0VOplRx86Uw-9kUqzOFytWLRkSn343y9ZPzsgQg6dnE)
> 
> 可以直接按Ctrl + V 复制在这里（复制成功后会显示一串地址）

**Comment by zyronon** [comment]
不好意思，忘记把测试代码删掉了。。。

现在脚本被举报了，脚本页面进不去，无法通过点击按钮更新
麻烦访问这个链接触发更新：
https://update.greasyfork.org/scripts/458024/V2EX%20Next%20V2Next.user.js

**Comment by wk333** [comment]
更新后ok了，真的很神奇，刚好出问题，结果更新地址还被举报了
建议再加一个备用地址，方便回退版本和更新
