### ISSUE TITLE
Chrome PWA 应用脚本不生效

### ISSUE THREAD

**Issue by hawcgn** [zyronon/V2Next#123]
1、是否在关闭其他插件和脚本后复现？

是

2、描述

在正常网页脚本没有问题  但是在PWA应用中  首次进入主页（技术tab）篡改侯中直接不显示该脚本  刷新也不生效  当我切换下tab  脚本神奇的加载了  

3、帖子ID
在这里填写帖子ID

4、截图

正常网页
![image](https://github.com/user-attachments/assets/c3df3ba5-fc92-4d33-a3a5-57f752237aff)

PWA应用
![image](https://github.com/user-attachments/assets/0f9858af-39b7-4af8-8e83-de476effc579)
![image](https://github.com/user-attachments/assets/5cb54865-a989-496c-b92c-9dc604669894)

**Comment by zyronon** [comment]
可能是网址规则没匹配到？

![image](https://github.com/user-attachments/assets/3f7b1064-9760-42c2-8e39-895a63fdcbe2)

你能看到pwa应用里面的网址吗？

**Comment by hawcgn** [comment]
> 可能是网址规则没匹配到？
> 
> ![image](https://private-user-images.githubusercontent.com/19986642/378292230-3f7b1064-9760-42c2-8e39-895a63fdcbe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDc1ODUsIm5iZiI6MTcyOTUwNzI4NSwicGF0aCI6Ii8xOTk4NjY0Mi8zNzgyOTIyMzAtM2Y3YjEwNjQtOTc2MC00MmMyLThlMzktODk1YTYzZmRjYmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEwNDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxODdkNDVjOTE1MGQ2MjU1ZmY1NzViOWE5NGI3ZWJiOWY4NGQyMjNmNTk0ODdlYzFkZmU5ODQxNDY3MTFmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MBei4AmLhgKv5Q23pckmMItoBsKSmzhG7WsB4Ejrrgk)
> 
> 你能看到 pwa 应用里面的网址吗？

![image](https://github.com/user-attachments/assets/722b1fdb-3043-448f-ad0d-7195cd19f0af)
https://www.v2ex.com/?from=pwa

![image](https://github.com/user-attachments/assets/cbd34c92-7d4f-4bdd-b917-ff55d652c071)

自定义加一条就可以了 👍

**Comment by hawcgn** [comment]
@zyronon 建议默认内置到`原始匹配`中

**Comment by zyronon** [comment]
> @zyronon 建议默认内置到`原始匹配`中

实际上是有的，我写的匹配规则是*.v2ex.com。按理说应该能匹配到www的

**Comment by hawcgn** [comment]
> > @zyronon 建议默认内置到`原始匹配`中
> 
> 实际上是有的，我写的匹配规则是 *.v2ex.com。按理说应该能匹配到 www 的

我理解应该是因为`?from=pwa`参数导致的吧
进入PWA应用默认是?from=pwa参数  没匹配导致没生效   切换了tab之后就匹配了?tab=*参数   然后脚本生效了
