### ISSUE TITLE
功能请求 imgur图片地址更换镜像源

### ISSUE THREAD

**Issue by yougg** [zyronon/V2Next#124]
这个脚本的功能只能在新打开的帖子页面生效
https://greasyfork.org/zh-CN/scripts/492194-imgur%E5%9B%BE%E7%89%87%E9%95%9C%E5%83%8F%E6%8D%A2%E6%BA%90
如果是在“弹框查看主题”中则没有效果
希望V2Net直接集成一下这个脚本生效

**Comment by zyronon** [comment]
好东西啊，我这imgur图片最近老是不显示，我一直以为是我梯子问题！

近期加上这个代码

**Comment by zyronon** [comment]
加上了

![image](https://github.com/user-attachments/assets/53308b8c-041b-44b0-ab26-6752064115d3)
