### ISSUE TITLE
问题报告：在油猴里开启了，但是没生效是什么原因

### ISSUE THREAD

**Issue by Absurd-BC** [zyronon/V2Next#125]

**Comment by zyronon** [comment]
你访问的地址是多少，有可能在匹配规则之外，没匹配到

**Comment by Absurd-BC** [comment]
> 你访问的地址是多少，有可能在匹配规则之外，没匹配到

https://www.v2ex.com/?tab=apple 这个地址

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/3bd9057d-51df-4562-8fed-d9fc24f73f74)

我这边测试了下，是生效的。你在无痕模式也是这样吗？有没有可能是冲突问题呢
