### ISSUE TITLE
功能请求：弹窗的功能按钮是否可以加一个新标签打开的功能

### ISSUE THREAD

**Issue by Bitzo** [zyronon/V2Next#126]
1、描述
主题弹窗这边是否会考虑加一个比如新标签打开的按钮呢， 参考 Arc peek 浏览模式的设计
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/af396a75-d257-47c4-927a-46bb8e3164ce">
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/2244192a-0d9c-4271-a77b-f7d76b040ff4">

  
2、这个功能解决了什么问题？
在 v 站有时候搜索某一个话题问答的时候，想暂时留下这个主题，一会还要参考，此时需要关闭弹簧后再去列表里点一次，加一个按钮可以减少操作步骤

**Comment by zyronon** [comment]
好的，近期加上

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/b0a497f2-3742-447d-ae91-068fa815bc50)
加上了

打开行为可以在设置里面设置

![image](https://github.com/user-attachments/assets/1ab8f938-8d4d-41b2-a08b-544674ecaab0)
