### ISSUE TITLE
markdown超链接解析成了帖子

### ISSUE THREAD

**Issue by AoEiuV020** [zyronon/V2Next#127]
1、是否在关闭其他插件和脚本后复现？

2、描述
```
<p><a href="https://imgur.com/a/JQ3DlGn" rel="nofollow">禁言图片</a>
```
帖子里这个文本原本是个超链接，点击跳转imgur图片页面，估计是发帖时用markdown格式写的，
插件解析后链接变成了
> https://www.v2ex.com/t/%E7%A6%81%E8%A8%80%E5%9B%BE%E7%89%87

等于导致这个图片没法查看了， 

3、帖子ID
1084674

4、截图

![image](https://github.com/user-attachments/assets/8d110cbb-3873-4002-bc62-406ef035063a)

**Comment by zyronon** [comment]
收到近期修复

**Comment by zyronon** [comment]
已修复
