### ISSUE TITLE
问题报告：图片未限制尺寸

### ISSUE THREAD

**Issue by montaro2017** [zyronon/V2Next#128]
1、是否在关闭其他插件和脚本后复现？
否

2、描述
帖子里的图片显示过大，超出屏幕和评论区

3、帖子ID
https://v2ex.com/t/1092231#24

24楼

4、截图

![image](https://github.com/user-attachments/assets/0643add5-2dec-4694-bab5-e3b54f3ba774)

加个`max-width: 100%`就可以了

**Comment by zyronon** [comment]
已修复
