### ISSUE TITLE
功能请求-能不能加个一键TOP的按钮

### ISSUE THREAD

**Issue by volcanoliu** [zyronon/V2Next#130]
1、描述
能不能加个一键TOP（回到顶部）的按钮
  
2、这个功能解决了什么问题？
现在每个帖子都会展开一部分内容，导致页面长了很多，翻到下面看完回到上面切换只能滚动条

**Comment by zyronon** [comment]
详情页，点标题返回顶部

首页（Ttab页），点下面的home icon，可以返回顶部
