### ISSUE TITLE
楼层过多停止解析楼中楼时，替换imgur源也会失效

### ISSUE THREAD

**Issue by leic4u** [zyronon/V2Next#134]
1、是否在关闭其他插件和脚本后复现？

是

2、描述

https://www.v2ex.com/t/846267 
以上帖子由于回复楼层过多，进入后即停止解析楼中楼，然后所有图片都无法加载了。（我使用的代理节点无法访问 imgur ）
其他正常解析楼中楼的帖子可以正常展示图片。

如果没有被 imgur 拒绝的代理节点的话，可以在代理规则里把 i.imgur.com 加入 direct 或 reject 后，让镜像源地址 img.noobzone.ru 加入代理，应该也能复现。

3、帖子ID
https://www.v2ex.com/t/846267

4、截图

![PixPin_2024-12-15_02-33-20](https://github.com/user-attachments/assets/5b406dac-6631-42c2-ae9a-070cfec3179d)
![PixPin_2024-12-15_02-35-22](https://github.com/user-attachments/assets/955050f0-c67d-4e3b-a483-bb5128516f01)

**Comment by zyronon** [comment]
目前是这样设计的，超过400层楼，脚本自动停止工作了，这种帖子一般都是盖楼贴，没有啥楼中楼的。另外楼层太多了，递归解析的时间也很长

**Comment by zyronon** [comment]
我的节点也被imgur拒绝了。。。

**Comment by leic4u** [comment]
这个替换 imgur 源的功能可不可以不随着楼中楼一起停止啊，确实很刚需，不然就要另外找个节点单独设个规则来解析 imgur 😂

**Comment by zyronon** [comment]
可以，后面有空改下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月18日 21:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [zyronon/V2Next] 楼层过多停止解析楼中楼时，替换imgur源也会失效 (Issue #134) |

这个替换 imgur 源的功能可不可以不随着楼中楼一起停止啊，确实很刚需，不然就要另外找个节点单独设个规则来解析 imgur 😂

**Comment by leic4u** [comment]
好的，感谢老哥！
