### ISSUE TITLE
楼中楼解析完成 点击显示，可以设置成自动显示吗

### ISSUE THREAD

**Issue by Sevlt** [zyronon/V2Next#138]
每次开一个新的帖子都要点击一下，感觉有些繁琐

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/9149bfe3-542b-420b-91b9-baa5609a40dc)

默认打开的，谁给你关了？

**Comment by zyronon** [comment]
我准备把这个功能去掉了，一开始是考虑下解析回复要耗一些时间，可以先正常浏览原版回复，等解析好了，再点开楼中楼查看。实际发现没有什么必要这样做

**Comment by Sevlt** [comment]
谢谢，一开始理解有误没 get 到是默认解析的意思。感觉这个功能挺好的，楼中楼用户应该都是希望长期一直这样的显示，如果去掉这个功能，感觉会有很多人有我发这个 issue 的问题🤣
