### ISSUE TITLE
这个帖子一直 loading

### ISSUE THREAD

**Issue by yam-liu** [zyronon/V2Next#14]
https://www.v2ex.com/t/937283?p=1

**Comment by zyronon** [comment]
看下你的网络请求， 是不是一直卡在哪次请求了？
这个帖子目前有4页，我会去请求剩下的3页。那3页如果没返回数据，就会一直loading。
![image](https://user-images.githubusercontent.com/19986642/236430779-b80aca33-c3f8-4896-b13c-eb0340b5d645.png)

我这边挺快就加载出来了
