### ISSUE TITLE
功能请求：新的标签页打开，建议修改成以下逻辑

### ISSUE THREAD

**Issue by Sevlt** [zyronon/V2Next#140]
目前有两个设置：新标签页打开、新标签也打开后马上切换过去

建议修改成只保留一个开关：打开新标签页，并且自动切过去

这样的逻辑和其他网站是一致的，要么当前页面前进打开，要么新标签页打开并且自动切过去。有时用户会新标签页打开很多帖子，然后逐一去看，常用做法是 cmd+点击（这样就是新标签页打开且不自动跳转），这个应该是浏览器的默认行为，如果像目前这样两个开关，如果都打开的话，那么浏览器的cmd+点击（新标签也打开且不自动跳转）就失效了。

**Comment by zyronon** [comment]
不会影响啊，我试了都开，鼠标中键和ctrl + 左键都可以正常新标签打开啊，没太理解到你的问题所在

“新标签页打开链接”：在新标签页打开链接，但不会马上切过去。这个表现和鼠标中键和ctrl + 左键是一样的

“打开新标签页时立即切换过去”：在新标签页打开链接，同时马上切过去。

打开了这两个选项也不会影响你鼠标中键和ctrl + 左键使用啊

**Comment by Sevlt** [comment]
两个开关都打开的话，那么 ctrl+单击的行为是【新标签页打开，并且切过去】，浏览器 ctrl+单击默认行为应该是【新标签页打开，但不切过去】，感觉覆盖浏览器默认行为是不是会不太合理

部分用户的需求是，日常使用是新标签页打开并且切过去看帖子，但也会经常用 ctrl+单击打开很多帖子（用 ctrl+单击，因为不会切过去所以可以很快速的在用新的标签打开很多个帖子），然后逐一点开看

**Comment by zyronon** [comment]
刚又试了下，的确如你所说，打开“打开新标签页时立即切换过去”时，ctrl + 单击的确也会立马切过去

**Comment by zyronon** [comment]
想了想，无解啊。你mac吗，没用鼠标是吧....

“新标签也打开后马上切换过去”这个功能是之前有人提issue，特意加上的

实际上你用鼠标的话，可以用按中键来避免这个问题

**Comment by Sevlt** [comment]
![image](https://github.com/user-attachments/assets/a933e07c-fba9-490a-bd81-a630740cfb8d)

对，mac+触控板🤣，不过我暂时把这两个按钮关闭，并且搭配链接助手这个插件实现新标签页打开帖子了，暂时满足了个人需求，感谢回复～
