### ISSUE TITLE
问题报告 /xna 不被视为普通节点

### ISSUE THREAD

**Issue by gwen31792** [zyronon/V2Next#141]
1、是否在关闭其他插件和脚本后复现？

是

2、描述

开启”新标签页打开链接“的设置后，在大部分节点间切换不会触发新标签页，但是VXNA（/xna）会打开新标签页

3、帖子ID

NOP

4、截图

![image](https://github.com/user-attachments/assets/b45f2c67-c541-45a9-85ba-fbe0d6848890)

**Comment by zyronon** [comment]
脚本在这个页面没生效，另外这个页面的帖子是站外网站
