### ISSUE TITLE
在节点下点击文章会打开新窗口

### ISSUE THREAD

**Issue by fsiisx** [zyronon/V2Next#15]
比如https://www.v2ex.com/go/bb?p=2

**Comment by zyronon** [comment]
![image](https://user-images.githubusercontent.com/19986642/236599579-91105554-6b0f-4be5-8af1-25366b972e5b.png)
出现这个没

**Comment by iks943** [comment]
出现了。
经过多次测试，表现如下，
在指定节点的模式下，查看第一条正常在当前页弹出详情框，从第二条开始，会变成打开新标签页查看。

**Comment by zyronon** [comment]
![568071a8b68940c066ffc208b01b6ef](https://user-images.githubusercontent.com/19986642/236659605-897822a8-03c4-4608-a776-5217c7c74939.jpg)

我邮箱收到通知，你有新的回复。但点进issue缺没有。

我这边还是无法复现，你在关闭其他脚本和插件的情况下能稳定复现吗？

**Comment by zyronon** [comment]
我邮箱收到通知，你有新的回复。但点进issue缺没有。

我这边还是无法复现，你在关闭其他脚本和插件的情况下能稳定复现吗？

**Comment by fsiisx** [comment]
经过仔细排查，是跟这个自动翻页的脚本有关，禁用这个就正常了。
https://github.com/XIU2/UserScript/blob/master/Autopage.user.js

**Comment by zyronon** [comment]
正常，他这个自动翻页脚本只是重新请求了v2的下一页，我这个脚本不会再执行一遍。

我之前做好了自动翻页，后面因为逻辑改了，把自动翻页去掉了，后续有空了加上
