### ISSUE TITLE
楼中楼显示错误？

### ISSUE THREAD

**Issue by gangdunizi** [zyronon/V2Next#17]
https://v2ex.com/t/938259
![1683534519091](https://user-images.githubusercontent.com/132885710/236775479-7cdbe0b0-50c8-4db0-ac80-0f2ea58f07d5.png)

**Comment by zyronon** [comment]
正确的，11楼和32楼，回复时并没有指定回复多少楼，只指定回复了“某个用户”，所以会  将其归类为  回复时指定的“某个用户”的 
 最后一次回复 的子级。毕竟脚本又不知道他想回复“某个用户”哪句话
