### ISSUE TITLE
哥们试试我这个改动

### ISSUE THREAD

**Issue by cweijan** [zyronon/V2Next#2]
你这个脚本很棒, 主要是悬浮框浏览帖子很方便, 但是加了很多东西跟牛皮癣一样, 我刚刚精简美化了一下, 你可以参考一下.

https://github.com/cweijan-depreacate/v2ex-script
[V2EX - 超级增强.user.zip](https://github.com/zyronon/v2ex-script/files/11209642/V2EX.-.user.zip)

**Comment by zyronon** [comment]
仔细看过你的提交，我做出了如下修复

- 移除切换栏 ：设置里面新增了“显示工具栏”选项，默认开启。
- 修复加载回复失败：未采纳，只要id，缺少/t不会请求失败吗？
- 间距优化：
   - 回到顶部按钮和关闭按钮，我修改了css样式，使其不再那么显眼，与V站的风格更搭配。
   - 正文的padding：部分采纳
 - 优化首页效果：设置里面新增了“列表hover时显示预览按钮”选项，默认开启。
 - 移除关闭按钮：调整了css样式。现在关闭按钮默认不会出现，只有关闭“点击两侧空白处关闭帖子详情”时才会出现
 - 移除详情框：同一
 - 隐藏回复线：调淡了线条颜色，回复线是仿照的reddit的设计，在视觉上更好区别楼中楼。后期会作类似贴吧那种回复，只有一层就好了
 - 增加灰色亮度：部分采纳，调低了回复分界线的亮度。背景未调整，你那个感觉太亮了
 - 后续提交：未采纳
 
我的大部分额外功能，都会在设置里面可以选择关闭，你可能没注意看

无论如何，感谢你的建议和反馈。我会在近期把修改发布到油猴上

**Comment by cweijan** [comment]
嗯嗯, 因为我是喜欢把软件改成符合自己习惯的, 只是如果顺便对你有帮助那就更好了.

**Comment by cweijan** [comment]
我现在用你的脚本回复和感谢都用不了, 因为那个base url是空的, 不知道你是做了魔法操作, 我之前是以为你没完全开源

**Comment by zyronon** [comment]
> 我现在用你的脚本回复和感谢都用不了, 因为那个base url是空的, 不知道你是做了魔法操作, 我之前是以为你没完全开源

用window共享数据就是这样，在脚本内的确能使用到值，但是在控制台打印就是undefined。
我也是刚发现这个问题[https://blog.rxliuli.com/p/e55a67646bf546b3900ce270a6fbc6ca](https://blog.rxliuli.com/p/e55a67646bf546b3900ce270a6fbc6ca)

现在回复和感谢不能用？这么离谱的嘛，我这可以，能否提供详细一点的日志说明？比如控制台的截图和请求时的截图
我更新了脚本，你可以装最新的看看[https://greasyfork.org/zh-CN/scripts/458024](https://greasyfork.org/zh-CN/scripts/458024)

**Comment by cweijan** [comment]
不是, 你的脚本可以, 但是我自己构建的不行, 所以我才改了那个地址.

**Comment by zyronon** [comment]
好吧，多半是跨域问题？。开发时，你是按照我的流程来搞的吗？一定要让浏览器可以跨域才可以！

```

1. 在硬盘新建一个空白目录。
2. 复制Chrome的快捷方式。然后右键新的快捷方式，点击属性，在属性弹框里面，点击上面的第二个Tab（快捷方式）
3. 找到目标，在输入框里面加上 --args --disable-web-security --disable-site-isolation-trials
   --user-data-dir=第一步建的目录地址（不用加引用）
   例："C:\Program Files\Google\Chrome\Application\chrome.exe" --args --disable-web-security
   --disable-site-isolation-trials --user-data-dir=C:\Users\abc\Documents\chrome2
4. 保存，然后双击打开这个快捷方式。这样子新打开的Chrome就允许跨域了
```

**Comment by cweijan** [comment]
原来是这样, 我嫌麻烦是直接打包后复制进脚本看效果.
