### ISSUE TITLE
与一个脚本冲突了

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [zyronon/V2Next#20]
同时开启了 [空格之王](https://greasyfork.org/zh-CN/scripts/37950-%E7%A9%BA%E6%A0%BC%E4%B9%8B%E7%8E%8B-%E8%87%AA%E5%8A%A8%E4%B8%BA%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC)这个脚本，发现开启这个脚本之后，增强功能的工具栏就无法显示了。

**Comment by zyronon** [comment]
未复现，贴下控制台看看报的什么错
