### ISSUE TITLE
反馈和建议

### ISSUE THREAD

**Issue by mrmyn** [zyronon/V2Next#23]
建议

<div type='discussions-op-text'>

能否像Chrome扩展程序V2EX PLUS那样：鼠标悬浮at用户时弹出双方的对话历史呢，楼中楼是挺好用，但是按照时间排序时还想看一下对应的聊天历史，一直在用，期待更好！
</div>

![image](https://github.com/zyronon/v2ex-script/assets/20763281/100b8474-aa5a-419b-94ad-9fbc47b0b458)

![image](https://github.com/zyronon/v2ex-script/assets/20763281/d1dd0f4f-ac5d-4e33-b999-e2dfbd2b6752)

**Comment by zyronon** [comment]
好，会出

**Comment by zyronon** [comment]
没那么快

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/1537a0cf-4314-4232-8e33-a17fa8ebcde5)
