### ISSUE TITLE
提议一个新功能：保存浏览过的主题的最大楼层，并对大于这个楼层的楼层进行颜色加亮标注。

### ISSUE THREAD

**Issue by 2435043xia** [zyronon/V2Next#24]
现在的一个痛点是当我看了一个主题，再次去看的时候因为楼中楼的关系，直接翻到最后会漏掉很多新的回复，但是一条一条把看过的回复再看一遍又会很蠢，这时候我就会切回原版。
这显然不是一个好的体验，我不清楚油猴可不可以缓存这些，这只是我一个简单的想法。

**Comment by zyronon** [comment]
好，TODO

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/c86662db-d928-4b07-b0b0-0d80f43dd524)

![image](https://github.com/zyronon/v2ex-script/assets/19986642/4e508012-d336-41a5-9d77-8dc81dc5c556)
