### ISSUE TITLE
@updateURL support

### ISSUE THREAD

**Issue by ehehaye** [zyronon/V2Next#25]
## 问题：
`@UpdateURL` field maybe not important in Tampermonkey on Chrome, but it's useful for Userscripts on Safari to check for updates. Hope to add this feature, or release it differently for the two platforms.

**Comment by zyronon** [comment]
这个我要怎么使用呢？我是用的@version来自动更新版本

**Comment by ehehaye** [comment]
> 这个我要怎么使用呢？我是用的@Version来自动更新版本

我不做脚本开发，大意应该是让 `@updateURL` 指向脚本的安装地址，类似这样

```
// @version      5.3
// @updateURL    https://greasyfork.org/scripts/458024-v2ex-%E8%B6%85%E7%BA%A7%E5%A2%9E%E5%BC%BA/code/V2EX%20-%20%E8%B6%85%E7%BA%A7%E5%A2%9E%E5%BC%BA.user.js
```

**Comment by zyronon** [comment]
ok，已加

**Comment by ehehaye** [comment]
> ok，已加

感谢支持，但我没能发现变化。我注意到 Greasy Fork 会针对`@updateURL`进行过滤，这或许是平台的特性：https://greasyfork.org/zh-CN/help/rewriting

另一种有效的方式，是将构建后的脚本文件上传至 Github（注意分支与版本控制），通过 raw 链接直接下载与安装，以下是我找到的一个脚本示例

https://github.com/axetroy/anti-redirect/raw/gh-pages/anti-redirect.user.js

**Comment by zyronon** [comment]
已加，需要更新到最新版本
