### ISSUE TITLE
请问给用户打的标签保存在哪里？

### ISSUE THREAD

**Issue by Mosney** [zyronon/V2Next#27]
设置页有这个开关 `用户打标签(跨平台，数据保存在自己的记事本)：`但此处这个记事本文件或者导出的地方在哪里？

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/24f96174-7453-499f-9e31-610784c75e1f)

**Comment by Mosney** [comment]
懂了，这样的话相当于根据V2EX账号同步了，非常感谢！

**Comment by zyronon** [comment]
是的😊
