### ISSUE TITLE
[页面改进]脚本设置页面布局好像是固定的

### ISSUE THREAD

**Issue by catna** [zyronon/V2Next#28]
## 问题：我的v站页面是设置过放大的, 默认倍率是150%(这样字大一些)
在点击脚本设置的时候, 发现设置panel 会布满显示区域并且没有看到关闭按钮

## 截图：
<img width="1720" alt="image" src="https://github.com/zyronon/v2ex-script/assets/13216533/3b88b3a7-97a1-40c0-8992-206884176045">

## 控制台报错：
无

## 期望:
改进布局显示, 或者增加一个关闭按钮 ❌

**Comment by zyronon** [comment]
目前是点击空白处关闭，你的意思是说，这个框弹出来已经全屏了吗？

**Comment by catna** [comment]
感谢回复
我描述的可能不是非常清楚, 我重新再描述一遍
=======================================
环境:
1. Chrome 浏览器, 暴力猴插件使用的该脚本
2. 默认Chrome 浏览器的显示是放大的, 倍率在150%

现象:
在放大环境下, 打开脚本设置会撑满显示区域, 导致没有办法点选空白区域关闭
所以, 我只能缩放回100%的尺寸后点选空白处关闭
=======================================
以上, 我这个只是一个小问题, 不影响逻辑功能上的使用

On Jun 29, 2023, at 11:10, Zyronon ***@***.***> wrote:



目前是点击空白处关闭，你的意思是说，这个框弹出来已经全屏了吗？

**Comment by zyronon** [comment]
已修复
