### ISSUE TITLE
反馈和建议

### ISSUE THREAD

**Issue by zmqking** [zyronon/V2Next#29]
### Discussed in https://github.com/zyronon/v2ex-script/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **zyronon** April 21, 2023</sup>
# 1、遇到$ is undefined或者Vue is undefined这种报错，请 **强制** 刷新页面重试，原因不明，偶现。

# 2、其他问题，先看设置里面能否解决，如下图
![image](https://github.com/zyronon/v2ex-script/assets/19986642/d516a97a-ebff-446d-82f1-76c5abaead1e)

# 3、确认是Bug或有好的建议请在本贴提出，最好带上控制台截图或者日志哦
</div>

**Comment by zmqking** [comment]
https://www.v2ex.com/t/953877#reply24 这种帖子，为啥没有登录会提示“没有权限”呢
![Snipaste_2023-07-04_14-35-59](https://github.com/zyronon/v2ex-script/assets/3350724/6f5520a0-d286-44d3-b106-758fff616581)
其它的帖子又没有这个问题！

**Comment by zyronon** [comment]
即使你关掉脚本，未登录时访问这个帖子就会302重定向首页。这个是V站的策略问题，和本脚本无关。

脚本只检测了http的状态码是否是302，是302的话就会前台提示没有权限。

有疑问可以在https://www.v2ex.com/go/feedback 这个节点发贴问站长
