### ISSUE TITLE
页面内打开的方式下，如果内容里有视频，关闭后不会停止播放

### ISSUE THREAD

**Issue by harrozze** [zyronon/V2Next#30]
## 问题：

以浮层的方式打开带有 youtube 视频的主贴，开始播放后，关闭当前打开的帖子，返回帖子列表（列表方式，非卡片）

这时听到视频的声音仍然在继续，没有停止播放。

猜测是只把浮层隐藏了，没有清空主贴内容，所以视频播放器还是正在播放的状态。

既然主贴内容已经在内存里，不需要反复抓取了，这时其实可以把浮层内容清空，重新打开时重新渲染

## 截图：

（无）

## 控制台报错：

（无）

**Comment by zyronon** [comment]
好的，了解

**Comment by zyronon** [comment]
我这边无法复现呢，关闭帖子详情弹框会把评论也删除掉啊，视频也无法播放了啊

你发一个出问题的帖子id呢
