### ISSUE TITLE
Feature Request: keyboard shortcut like gmail

### ISSUE THREAD

**Issue by harrozze** [zyronon/V2Next#31]
列表页面（前提：列表页时先锁定最上面的一篇作为“当前选定”，边框加粗）：
j - 下一篇
k - 上一篇
Enter: 打开详情
gNUM - 进入序号为 NUM 的收藏节点
gi - 返回首页

详情页：
j - 下一篇
k - 上一篇
r - 回复
u/Esc - 返回列表页（当前节点，或首页）

**Comment by zyronon** [comment]
todo
