### ISSUE TITLE
添加标签失败

### ISSUE THREAD

**Issue by tomcatq** [zyronon/V2Next#32]
## 截图：
![image](https://github.com/zyronon/v2ex-script/assets/37393124/cf7efa85-06bd-401d-98c4-3135ca9c1ccb)

## 控制台报错：
![image](https://github.com/zyronon/v2ex-script/assets/37393124/d0223c84-2248-4dab-917c-bd8789f6838c)
![image](https://github.com/zyronon/v2ex-script/assets/37393124/dce6563a-6d45-4175-a96b-5d7c34fb2406)

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
未复现，能否提供如下的请求截图？

![image](https://github.com/zyronon/v2ex-script/assets/19986642/88454df8-54f3-4041-9977-c2119259dcfb)
只要note相关的

**Comment by tomcatq** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/37393124/3f052456-e082-40a8-ba63-3c9c03a8b5f2)
![image](https://github.com/zyronon/v2ex-script/assets/37393124/7e094402-1487-4669-b304-486cfd3c4eac)

**Comment by zyronon** [comment]
已修复
