### ISSUE TITLE
标签的删除被遮挡

### ISSUE THREAD

**Issue by iulo** [zyronon/V2Next#35]
## 问题：
标签多的时候无法编辑
## 截图：
<img width="770" alt="image" src="https://github.com/zyronon/v2ex-script/assets/6769037/999c8fcf-b413-437e-aca8-875dcab54e53">

hover状态
<img width="787" alt="image" src="https://github.com/zyronon/v2ex-script/assets/6769037/9eca8e3b-dfd1-4950-a99e-812029d9e888">

其他按钮显示导致标签的删除按钮被遮挡
## 控制台报错：
无

**Comment by iulo** [comment]
另外能否在member详情页增加标签的显示编辑
https://www.v2ex.com/member/zyronon
<img width="926" alt="image" src="https://github.com/zyronon/v2ex-script/assets/6769037/1c2e4fe5-eadd-4d95-8425-3564fcbf53df">
在这块加

**Comment by zyronon** [comment]
收到，近期会修复

**Comment by zyronon** [comment]
已修复
