### ISSUE TITLE
BUG：会将一些不是图片的URL解析成图片

### ISSUE THREAD

**Issue by zccat** [zyronon/V2Next#37]
## 问题：
会将一些不是图片的URL解析成图片
## 截图：
![image](https://github.com/zyronon/v2ex-script/assets/46469775/eb530df9-fd91-45b8-ab0a-492bc3c370c8)
这是不使用插件的效果
![image](https://github.com/zyronon/v2ex-script/assets/46469775/e7a47f2d-64bb-4a33-a005-63d2d22c2a92)
这是使用插件的效果
![image](https://github.com/zyronon/v2ex-script/assets/46469775/5cd7f7d1-a430-485e-9f0b-842bea7ccc06)
使用插件后，HTML代码

## 控制台报错：
控制台无报错

**Comment by zyronon** [comment]
好的，收到

**Comment by zyronon** [comment]
已修复
