### ISSUE TITLE
FR：能否支持设置项随油猴导出而导出？

### ISSUE THREAD

**Issue by LoneFireBlossom** [zyronon/V2Next#38]
就像 https://github.com/the1812/Bilibili-Evolved 这样，我导出油猴（Tampermonkey）的所有脚本时其所有设置项也都被导出了，方便换机和换浏览器。

**Comment by pockyneko** [comment]
直接拉本地文件呗

**Comment by LoneFireBlossom** [comment]
> 直接拉本地文件呗

没看懂，本地文件指的是？

**Comment by zyronon** [comment]
收到

**Comment by pockyneko** [comment]
抱歉，看错你的问题了
