### ISSUE TITLE
在使用详情框的状态下回帖，在中文输入的过程中按esc会退回到主页面

### ISSUE THREAD

**Issue by 0f7b90** [zyronon/V2Next#4]
有时候输入过程中打错字了会按esc重新输入，但这同时也退出了详情框显示的帖子，很不方便
macos Ventura + safari

**Comment by zyronon** [comment]
已修复，现在输入框聚焦时按esc不会关闭弹框

**Comment by 0f7b90** [comment]
> 已修复，现在输入框聚焦时按esc不会关闭弹框

更新了，但问题还是一样（搜狗输入法）
https://imgur.com/a/IzwlP30

**Comment by zyronon** [comment]
和输入法没关系，现在的代码是输入框聚焦，就esc事件就失效了，你看下呢你点到输入框不打字按esc能关闭吗

**Comment by 0f7b90** [comment]
> 和输入法没关系，现在的代码是输入框聚焦，就esc事件就失效了，你看下呢你点到输入框不打字按esc能关闭吗

进输入框不打字的状态下按esc不会关闭，打字过程中按esc就关闭了

**Comment by zyronon** [comment]
那有点奇怪，我研究下

**Comment by zyronon** [comment]
无法解决

**Comment by zhuziyi1989** [comment]
> 无法解决

这基本是一个高频 bug，按 Esc 后再次进入，评论会被清空，如果确实无法修复，建议禁止按键 Esc 事件，再不济给个退出提示也行...

**Comment by Felix2yu** [comment]
加一个配置选项禁止Esc关闭吧

**Comment by zyronon** [comment]
现在在输入状态下，按esc不会关闭弹框啊？只有不在输入框不聚焦了，按esc才会关闭啊

**Comment by Felix2yu** [comment]
> 现在在输入状态下，按esc不会关闭弹框啊？只有不在输入框不聚焦了，按esc才会关闭啊

在输入框直接按esc确实不会关闭，但是在输入框中输入法打字选词下我想按esc不让候选词上屏情况下会直接退，并且清空正在输入框中所有文字

**Comment by zyronon** [comment]
@Felix2yu 好吧，我用的windows自带的输入法，在选词过程中按esc，也不会关闭弹框。。。

看样子你们用的第三方输入法，我后面看看

**Comment by Felix2yu** [comment]
我是macOS+Safari+RIME鼠须管输入法，饱受这个问题困扰

**Comment by whjstc** [comment]
太痛苦了，微信输入法
