### ISSUE TITLE
 开启脚本后，Mac端CMD+Enter快捷键无效

### ISSUE THREAD

**Issue by LoneFireBlossom** [zyronon/V2Next#40]
不开这个脚本的话，Mac端v2ex发帖时可以用cmd+enter发帖，就不用点那个发送按钮了。也就是说，cmd+enter和ctrl+enter都是发帖的快捷键。
开了这个脚本的话，cmd+enter快捷键就失效了。
在Monterey 12.7.1， Safari 17，Chrome目前最新版测试是这样的

**Comment by zyronon** [comment]
好的，收到

**Comment by LoneFireBlossom** [comment]
> 好的，收到

感谢大佬的脚本，感觉很好用，因为能把所有回复页聚合在一起，平时用singlefile保存帖子更方便了😄

**Comment by zyronon** [comment]
已在7.6版本修复
