### ISSUE TITLE
希望设置项能在v2ex的多个域名中通用

### ISSUE THREAD

**Issue by LoneFireBlossom** [zyronon/V2Next#41]
v2ex有 jp.v2ex.com, fast.v2ex.com, cn.v2ex.com, global.v2ex.com等多个域名，而本脚本的设置项在每个xxxx.v2ex.com里都是独立的，都要单独进行设置，这样很不方便。
我平时自然是打开www.v2ex.com查看的，但是谷歌搜索时我会搜`关键词 site:v2ex.com`，因为感觉这样搜索范围应该更广一些。所以希望本脚本能统一所有`*.v2ex.com`下的设置，一次设置处处适用。

**Comment by zyronon** [comment]
这个没办法，设置保存在本地的，如果想在保存在云端就需要服务器或者存在V2ex的记事本里面。读取V2ex的记事本的数据超级慢，比如说一打开帖子默认是卡片是布局，读取完V2ex的记事本，几秒后，发现是表格布局，界面一下就变了，那样搞的话体验不好

保存在本地，只有当前域名能读取到数据。
