### ISSUE TITLE
脚本开启后作为OP，APPEND按钮消失了

### ISSUE THREAD

**Issue by Webhea-zzx** [zyronon/V2Next#42]

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/4e9ce78e-fb53-4c3c-b575-f5e2963b29b3)

有的呀

**Comment by zyronon** [comment]
是不是其他插件冲突了，把其他插件关掉试试
