### ISSUE TITLE
鼠标侧键返回

### ISSUE THREAD

**Issue by pockyneko** [zyronon/V2Next#44]
## 问题：
用鼠标侧键返回，第一次会显示所有的回复信息，而且页面是空白的，点第二次侧键才能返回到原来的界面
## 截图：
![image](https://github.com/zyronon/v2ex-script/assets/114719186/9852c056-5daf-4fb9-91cf-0188ed323880)

**Comment by pockyneko** [comment]
“第一次会显示所有的回复信息，而且页面是空白的”说显示所有的回复消息是指url后面自动添加#reply{回复数}

**Comment by zyronon** [comment]
收到
