### ISSUE TITLE
图片解析建议特殊兼容一下imgur网页地址

### ISSUE THREAD

**Issue by AoEiuV020** [zyronon/V2Next#46]
## 问题：
好多人会错误发布imgur图片的网页地址，不会被v2ex识别成图片，反而被v2ex-script识别成了图片地址但加载不出来，
比如，
https://imgur.com/a/Gl0ifQ7
实际图片直链是，
https://i.imgur.com/j3Qy2eB.png
建议想办法识别一下imgur网页地址，不行就直接不解析吧，

## 截图：

![image](https://github.com/zyronon/v2ex-script/assets/11682198/64d6cba9-b173-491d-9f27-7c29295610de)

**Comment by pockyneko** [comment]
+1 遇到直接贴网址的会指出来image但是点了没反应，连网址都不显示出来      未用插件
![image](https://github.com/zyronon/v2ex-script/assets/114719186/2fd84fcd-b9b8-42b4-b166-9a4114f2487b)
用插件后
![image](https://github.com/zyronon/v2ex-script/assets/114719186/9071afce-c913-4c67-94e0-3ac1e126bb70)

**Comment by zyronon** [comment]
已在7.4版本修复
