### ISSUE TITLE
帖子显示不正确

### ISSUE THREAD

**Issue by lyaaz** [zyronon/V2Next#49]
## 问题：
7位帖子ID如 1000016，加载时会被截断为6位 100001，导致显示错误的帖子内容

**Comment by EkkoG** [comment]
贴子数达到一百万，出 bug 了

**Comment by 0817weakback** [comment]
显示不正确+1.

**Comment by EkkoG** [comment]
PR 合并前，可以临时把 4622 行的 9 改成 10 解决

```diff
---          id = href.substring(href.indexOf("/t/") + 3, href.indexOf("/t/") + 9);
+++          id = href.substring(href.indexOf("/t/") + 3, href.indexOf("/t/") + 10);

```

**Comment by xinhochen** [comment]
改成这样更好吧：
//id = new URL(href).pathname.substring(3); a已经是一个URL对象了，不用重复new
id = a.pathname.substring(3);

**Comment by EkkoG** [comment]
不熟悉项目所以个人偏向于不修改使用的 API，是数字引起的问题只修改数字

**Comment by xinhochen** [comment]
因为你这样改到了后面超过一千万又不行了。而且，对于像 https://www.v2ex.com/t/999887?p=1#reply47 这样的URL，解析出来的id值是错的

**Comment by EkkoG** [comment]
是的，我只是提个风险最小的紧急修复而已，不是来解决根本问题的

PS：一千万能不能到还是个问题，能也是很久以后的事了

**Comment by xinhochen** [comment]
就是说你的修复方案能解决大于一百万的id值的问题，但是引入了对小于一百万的id值的解析错误

**Comment by EkkoG** [comment]
我试了打开小于一百万的贴子没有问题

**Comment by xinhochen** [comment]
那可能其它地方有处理吧，从代码上来看，你的解析出来的id值最后会跟一个符号

**Comment by EkkoG** [comment]
建议先试一下有没有问题再讨论 https://www.v2ex.com/recent?p=32792

**Comment by aitianci** [comment]
好家伙这种千年虫问题居然重出江湖

**Comment by AoEiuV020** [comment]
v站千年虫，请优先修复更新一下，@zyronon

**Comment by xinhochen** [comment]
> 建议先试一下有没有问题再讨论 https://www.v2ex.com/recent?p=32792

我的方案没有问题

**Comment by AoEiuV020** [comment]
> > 建议先试一下有没有问题再讨论 https://www.v2ex.com/recent?p=32792
> 
> 我的方案没有问题

那就开个pr吧，

**Comment by EkkoG** [comment]
> > 建议先试一下有没有问题再讨论 https://www.v2ex.com/recent?p=32792
> 
> 我的方案没有问题

没有说你的方案有问题的，我是说我提 PR 的紧急修复是基本不改现有使用的 API 来考虑的，这样风险小，而且我试过了一百万，十万，以及十万以下都没有问题才提的 PR，你对这个方案提出的疑问都只是基于「觉得」这个方案有问题而提出的，实际上这个方案是不完美，但是现在是没有问题的，你觉得有问题是没有有试，而我试了，所以我觉得你试了一下再讨论比较好，至少不会得出针对十万级别 ID 的贴子有问题这样的结论，只是这样

建议你提个 PR 吧，能一劳永逸的解决问题当然是更好的

**Comment by zyronon** [comment]
汗流浃背了😃，马上改兄弟们

**Comment by zyronon** [comment]
相关 bug ，已于最新版本(7.8.1)修复，地址： https://greasyfork.org/zh-CN/scripts/458024 。未自动更新的兄弟需要手动更新一下，或等待下次浏览器启动时自动更新

@EkkoG @aitianci @AoEiuV020 @xinhochen

**Comment by AoEiuV020** [comment]
ok了，期待v站万年虫，希望v站和脚本能坚持到那个时候，

**Comment by xinhochen** [comment]
> 相关 bug ，已于最新版本(7.8.1)修复，地址： https://greasyfork.org/zh-CN/scripts/458024 。未自动更新的兄弟需要手动更新一下，或等待下次浏览器启动时自动更新
> 
> @EkkoG @aitianci @AoEiuV020 @xinhochen

感谢作者大大的及时修复！
可否考虑下我上面讨论的修复方案，逻辑更简单，适用范围也更广：
id = a.pathname.substring('/t/'.length);

**Comment by zyronon** [comment]
> > 相关 bug ，已于最新版本(7.8.1)修复，地址： https://greasyfork.org/zh-CN/scripts/458024 。未自动更新的兄弟需要手动更新一下，或等待下次浏览器启动时自动更新
> > @EkkoG @aitianci @AoEiuV020 @xinhochen
> 
> 感谢作者大大的及时修复！ 可否考虑下我上面讨论的修复方案，逻辑更简单，适用范围也更广： id = a.pathname.substring('/t/'.length);

6，你这个更好，比我那个判断好，我改了
