### ISSUE TITLE
右侧的今日热议主题不是用浮层打开的，还是会跳转新页面

### ISSUE THREAD

**Issue by yam-liu** [zyronon/V2Next#5]
另外还有个小问题，浮层的关闭方式有点麻烦。如果用 vimium 浏览，每次都需要 F 一下再按标签。希望可以定制 Esc 等键直接关闭浮层。

**Comment by zyronon** [comment]
热议主题是用浮层打开的啊，你装了其他的脚本吗？
弹框可以用Esc关闭啊，不用F一下

你装的是最新版本3.2.6吗?

**Comment by yam-liu** [comment]
嗯，试了下，应该是其他影响的，我找找是哪个。
