### ISSUE TITLE
好像不适配手机端

### ISSUE THREAD

**Issue by kokojacket** [zyronon/V2Next#51]
手机端使用有扩展的浏览器，发现好像不太适配

**Comment by zyronon** [comment]
是的，没有专门适配手机端。没人用也就没动力做，下载量和star数还没主打UI美化的V2EX_Polish高😅😅😅

**Comment by kokojacket** [comment]
刚从V2EX_Polish切换过来，那个确实有点小Bug.
大佬多推广推广~
