### ISSUE TITLE
打开帖子加载较慢

### ISSUE THREAD

**Issue by wk333** [zyronon/V2Next#56]
可能是计算楼中楼排列的比较复杂？导致转圈1秒或者重新打开才能显示帖子内容

不知道能否优化，有点影响体验

**Comment by zyronon** [comment]
# 把其他脚本或插件关闭掉再进行测试

少于100楼的楼中楼解析几乎不花时间。转圈是请求帖子内容导致的，一直转圈是你网有问题，可以看下f12里面的网络请求是不是卡住了，v2迟迟不返回就会一直转圈

**Comment by wk333** [comment]
难顶，感觉用clash测100多的延迟也不算慢了
单独打开帖子加载就很快

**Comment by zyronon** [comment]
单独打开时，返回的网页里面有评论，直接拿到之后解析楼中楼了，肯定快啊又不请求一遍。

在主页打开帖子时，要先请求帖子内容，然后解析评论，拿到所有评论之后，才会递归循环去解析楼中楼。

![image](https://github.com/zyronon/v2ex-script/assets/19986642/15d6bd60-d5a7-4791-accd-44bc92d72847)

你要测试就看 下面网络请求里面的pending 变动200之后，上面的圈圈是否消失？我这基本上，pending变成200之后，圈圈1秒不到就消失了，几乎是同步的。

**Comment by wk333** [comment]
我的是这样的，也可能偶尔机场抽风吧，习惯楼中楼还有点离不开
![image](https://github.com/zyronon/v2ex-script/assets/30464860/4150fb66-6815-45ff-9615-677f40519985)
