### ISSUE TITLE
发送回复带尖括号的情况发送后的回显会吞文字

### ISSUE THREAD

**Issue by AoEiuV020** [zyronon/V2Next#57]
## 问题：
发送带尖括号的回复比如，
sudo passwd \<username\>
发送成功看到自己发送的消息却只有sudo passwd，
我以为是v2ex吞了\<username\>但刷新后又出现了，

## 截图：
![image](https://github.com/zyronon/v2ex-script/assets/11682198/5b95d1ac-9122-42a8-b3b7-848c83293409)
![image](https://github.com/zyronon/v2ex-script/assets/11682198/ae6e812f-cb1a-44e5-aea3-f307e45298a4)
![image](https://github.com/zyronon/v2ex-script/assets/11682198/328a8632-9d0c-41ad-8b2d-17f9e5e7fe71)

**Comment by zyronon** [comment]
收到
