### ISSUE TITLE
标题和下面的评论对不上

### ISSUE THREAD

**Issue by frankkly** [zyronon/V2Next#58]
## 问题：
和之前点开完全错误的那个bug稍微有点不同
这一次是顶部的标题和内容是对的，下面的回复变成另一个帖子的了
## 截图：
<img width="1274" alt="image" src="https://github.com/zyronon/v2ex-script/assets/10302584/6afa3947-7287-4376-9600-72e2e66d07ca">

**Comment by zyronon** [comment]
快速点击了吧，点开上一个，然后马上关闭又点开下一个就会这样
