### ISSUE TITLE
弹框显示的网页标题问题

### ISSUE THREAD

**Issue by yuuuxt** [zyronon/V2Next#59]
## 问题：
弹框显示关闭后标题留在前一个打开的标题而未恢复, 

需要恢复或直接锁定不随弹框变动.

**Comment by zyronon** [comment]
![image](https://github.com/zyronon/v2ex-script/assets/19986642/eb29fbcb-7637-4df3-a754-39449b85c5df)

如果手动安装了新的脚本，看下原来的V2EX - 超级增强是否还在，需要卸载掉

**Comment by yuuuxt** [comment]
目前不存在别的v2脚本, 环境是firefox - violentmonkey

**Comment by zyronon** [comment]
> 目前不存在别的v2脚本, 环境是firefox - violentmonkey

firefox下的确存在这个问题，已修复，点击这里重装安装一下 https://greasyfork.org/zh-CN/scripts/458024
