### ISSUE TITLE
关闭高赞回复，页面仍会loading

### ISSUE THREAD

**Issue by xiecang** [zyronon/V2Next#64]
## 问题：
1. 关闭高赞回复，页面仍会有高赞回复部分的 loading， 

2. 折叠长文后，点击展开主题无效（Firefox Tampermonkey 5.0.1）控制台无报错，未绑定事件
[测试帖子](https://www.v2ex.com/t/1010514)
## 截图：
![image](https://github.com/zyronon/web-scripts/assets/16369161/3f4f0dd7-e12d-4962-ae72-b6ac51331874)

**Comment by xiecang** [comment]
感谢大佬修复，目前还有一个小问题，影响不大，麻烦有空看一下
这个[测试帖子](https://www.v2ex.com/t/1010514) 楼中楼 `楼中楼解析完成 点击显示` 按钮，点击之后，正文没有了
<img width="803" alt="image" src="https://github.com/zyronon/web-scripts/assets/16369161/57e00f78-f39e-46aa-95d6-2850c8f0c266">

控制台报错截图如下：
<img width="522" alt="image" src="https://github.com/zyronon/web-scripts/assets/16369161/f89ca51f-19ea-4fb6-83d5-c0ec17b8af46">

<img width="686" alt="image" src="https://github.com/zyronon/web-scripts/assets/16369161/da7e6f4d-4ff0-4cbb-ba1a-b2261ccc1a41">

**Comment by zyronon** [comment]
已修复，https://greasyfork.org/zh-CN/scripts/458024
