### ISSUE TITLE
启用脚本后会被V2ex ban ip

### ISSUE THREAD

**Issue by sunrisewestern** [zyronon/V2Next#65]
## 问题：
启用脚本后会被V2ex ban ip。 换了几个 ip，只要启用脚本几秒就被 ban 了

## 截图：
<img width="792" alt="image" src="https://github.com/zyronon/web-scripts/assets/24836848/ab4fca2c-eb5f-4132-b772-0028aed2237e">

**Comment by raikiriww** [comment]
我的 ip 今天也被 ban 了。不知道是不是这个原因。

**Comment by zyronon** [comment]
我根本都无法访问v2，v2好像挂了？

**Comment by renfei** [comment]
https://www.v2ex.com/t/1010835

**Comment by CJaeson** [comment]
停用脚本是不是就能访问了？

**Comment by zhf883680** [comment]
我不确定这是攻击还是某个插件的行为，很多的 IP 持续在以非常高的并发请求 /api/topics/show.json 这个接口。因为我一直没有安装过任何插件，所以我无法去确认这是否是任何插件造成的问题。只能针对这个访问特征当作攻击来应对了。

站长的回复  
这个ip的会被block

**Comment by renfei** [comment]
> 停用脚本是不是就能访问了？

站长回复：

目前 CF 上的 Rate Limit 设置是：

如果 10 秒内超过 5 个请求 /api/topics/show.json ，IP 会被 ban 一天。

**Comment by Xavier9896** [comment]
https://github.com/zyronon/web-scripts/blob/bee70bb97635968e4dbd6c8e2d600a5b5abb86f3/v2next/mobile/src/main.ts#L451-L464

![image](https://github.com/zyronon/web-scripts/assets/34981520/f68abbde-ca7d-49f0-ac5e-92bdb52599e6)
请求太多了，列表 forEach 把服务器干掉了，快改改吧 @zyronon

**Comment by zyronon** [comment]
收到收到，我马上改

**Comment by zyronon** [comment]
我现在进都进不去v站，你们谁帮我回一下站长 @renfei @CJaeson @zyronon @zhf883680 @sunrisewestern 

内容如下 

@Livid 站长您好，我是V2Next的脚本作者，脚本的确会请求很多次show.json这个接口，并不是在刻意攻击V站

脚本逻辑是：

1、每次打开首页或者节点这种列表页面，脚本会解析列表中的所有主题拿到id，然后并发请求show.json，以获取接口返回的content_rendered这个字段。

2、这个字段我主要用于列表页的卡片模式，和弹框显示主题时提前显示正文

这里是脚本地址：https://greasyfork.org/zh-CN/scripts/458024

这个脚本是我今年1月份上传，这个show.json的逻辑也是一开始就存在的，并不是最近才加的功能，并不是在刻意攻击V站

可能是最近使用我这个脚本的V站用户比较多，我看这个统计数据 https://greasyfork.org/zh-CN/scripts/458024-v2next/stats ，最近一次脚本更新的人数有1700人，说明可能有1000以上的人在使用这个脚本，由于突然用户过多，导致请求数量也变的更多，所以被站长判定为攻击行为了

我会把这个逻辑修改掉，在此很抱歉给站长带来困扰了

**Comment by Xavier9896** [comment]
> 我现在进都进不去v站，你们谁帮我回一下站长 @renfei @CJaeson @zyronon @zhf883680 @sunrisewestern
> 
> 内容如下
> 
> @livid 站长您好，我是V2Next的脚本作者，脚本的确会请求很多次show.json这个接口，并不是在刻意攻击V站
> 
> 脚本逻辑是：
> 
> 1、每次打开首页或者节点这种列表页面，脚本会解析列表中的所有主题拿到id，然后并发请求show.json，以获取接口返回的content_rendered这个字段。
> 
> 2、这个字段我主要用于列表页的卡片模式，和弹框显示主题时提前显示正文
> 
> 这里是脚本地址：https://greasyfork.org/zh-CN/scripts/458024
> 
> 这个脚本是我今年1月份上传，这个show.json的逻辑也是一开始就存在的，并不是最近才加的功能，并不是在刻意攻击V站
> 
> 可能是最近使用我这个脚本的V站用户比较多，我看这个统计数据 https://greasyfork.org/zh-CN/scripts/458024-v2next/stats ，最近一次脚本更新的人数有1700人，说明可能有1000以上的人在使用这个脚本，由于突然用户过多，导致请求数量也变的更多，所以被站长判定为攻击行为了
> 
> 我会把这个逻辑修改掉，在此很抱歉给站长带来困扰了

帮你回复了。
另外你也可以自己联系站长：https://discord.gg/GNUzSQQSYw
https://staging.v2ex.com/t/1010835#reply49

**Comment by CJaeson** [comment]
> 我现在进都进不去v站，你们谁帮我回一下站长 @renfei @CJaeson @zyronon @zhf883680 @sunrisewestern 
> 
> 
> 
> 内容如下 
> 
> 
> 
> @Livid 站长您好，我是V2Next的脚本作者，脚本的确会请求很多次show.json这个接口，并不是在刻意攻击V站
> 
> 
> 
> 脚本逻辑是：
> 
> 
> 
> 1、每次打开首页或者节点这种列表页面，脚本会解析列表中的所有主题拿到id，然后并发请求show.json，以获取接口返回的content_rendered这个字段。
> 
> 
> 
> 2、这个字段我主要用于列表页的卡片模式，和弹框显示主题时提前显示正文
> 
> 
> 
> 这里是脚本地址：https://greasyfork.org/zh-CN/scripts/458024
> 
> 
> 
> 这个脚本是我今年1月份上传，这个show.json的逻辑也是一开始就存在的，并不是最近才加的功能，并不是在刻意攻击V站
> 
> 
> 
> 可能是最近使用我这个脚本的V站用户比较多，我看这个统计数据 https://greasyfork.org/zh-CN/scripts/458024-v2next/stats ，最近一次脚本更新的人数有1700人，说明可能有1000以上的人在使用这个脚本，由于突然用户过多，导致请求数量也变的更多，所以被站长判定为攻击行为了
> 
> 
> 
> 我会把这个逻辑修改掉，在此很抱歉给站长带来困扰了
> 
> 

你可以访问这个进入https://staging.v2ex.com/

**Comment by anghunk** [comment]
不用每次打开网站都请求一次接口，可以做成缓存，如果之前请求过的可以使用，新帖子再单独请求一遍，不然太废性能了...

**Comment by zyronon** [comment]
好了，兄弟更新一下，直接去掉了请求了。后面再想办法优化吧
