### ISSUE TITLE
url不对

### ISSUE THREAD

**Issue by howiegugu** [zyronon/V2Next#67]
最新的版本。点开帖子刷新后又回到主页，看了下点开帖子后url还是保持主页的url，所以刷新时又跳回主页。关了插件后就正常了

**Comment by howiegugu** [comment]
![image](https://github.com/zyronon/web-scripts/assets/128498171/d3ccc63f-0d3f-4e9f-b0ef-4f3a6fee9ca7)

**Comment by zyronon** [comment]
嗯，知道，最近会修复

**Comment by zyronon** [comment]
已修复 https://greasyfork.org/zh-CN/scripts/458024
