### ISSUE TITLE
刚发的主题无法编辑

### ISSUE THREAD

**Issue by AoEiuV020** [zyronon/V2Next#69]
## 问题：
自己发的帖子，十分钟内可以 move 可以 edit， 不能 append，
## 截图：
![image](https://github.com/zyronon/web-scripts/assets/11682198/ff45f9a9-d4b4-481f-9c2a-db270f3fc102)

**Comment by zyronon** [comment]
已修复 https://greasyfork.org/zh-CN/scripts/458024

**Comment by zyronon** [comment]
你连star都没点😔😔

**Comment by AoEiuV020** [comment]
@zyronon 哈哈，作者还在纠结star比不过竞品的事吗，真没必要纠结这个数字，小心走火入魔哪天想不开去买star,
就我个人而言我是不star正在用的项目和在其他渠道有关注的项目，只star想抽空看代码的防丢失，
