### ISSUE TITLE
新标签页打开

### ISSUE THREAD

**Issue by Huozzzy** [zyronon/V2Next#70]
## 问题：
新标签页打开可以改成前台显示嘛？现在新标签页打开是后台开一个标签页，还需要手动去换标签页

**Comment by zyronon** [comment]
已添加，https://greasyfork.org/zh-CN/scripts/458024

![image](https://github.com/zyronon/web-scripts/assets/19986642/342e60d3-f1b5-4fa4-8977-0c244fb54285)

**Comment by zyronon** [comment]
你连star都没点！😌

**Comment by Huozzzy** [comment]
> 你连star都没点！😌

点上了
