### ISSUE TITLE
用户信息页面链接点击没反应

### ISSUE THREAD

**Issue by AoEiuV020** [zyronon/V2Next#71]
## 问题：
查看用户历史主题和回复的页面，链接点击只修改了地址栏，没有打开主题，

## 截图：
![image](https://github.com/zyronon/web-scripts/assets/11682198/d2e3e4b4-b32f-4c28-934c-76e332919c7e)

**Comment by zyronon** [comment]
更新到最新版本 https://greasyfork.org/zh-CN/scripts/458024
