### ISSUE TITLE
开启新标签页打开链接会导致脚本设置入口有问题

### ISSUE THREAD

**Issue by snachx** [zyronon/V2Next#73]
## 问题：
开启 新标签页打开链接
点击 脚本设置
Safari 会切换到新标签页并报错提示不允许在智能搜索栏使用 Javascript
按提示信息设置之后不报错但会切换到空白标签页，需要自己切换回原来的标签页
## 截图：
![CleanShot 2024-02-02 at 15 20 56@2x](https://github.com/zyronon/web-scripts/assets/2197143/9735424b-d789-4f98-85aa-da5faac7c738)

**Comment by zyronon** [comment]
最新版本已修复，但手头没有mac可测试😥。https://greasyfork.org/zh-CN/scripts/458024-v2next

**Comment by snachx** [comment]
更新验证了一下已经可以了
