### ISSUE TITLE
楼中楼下拉框显示空白

### ISSUE THREAD

**Issue by tjx0722** [zyronon/V2Next#74]
## 问题：
楼中楼下拉框显示空白
## 截图：
![image](https://github.com/zyronon/web-scripts/assets/42849881/32c561bd-4563-4d71-a939-3692f28d3368)

## 控制台报错：
![image](https://github.com/zyronon/web-scripts/assets/42849881/36c54dfc-782f-44cd-84f7-a78a5190c76c)

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
已修复 https://greasyfork.org/zh-CN/scripts/458024-v2next

**Comment by tjx0722** [comment]
> 已修复 https://greasyfork.org/zh-CN/scripts/458024-v2next

优秀
