### ISSUE TITLE
跨平台给用户打标签这个功能有开放计划吗？

### ISSUE THREAD

**Issue by leic4u** [zyronon/V2Next#75]
拥有的时候没有珍惜，失去了才追悔莫及。

**Comment by zyronon** [comment]
现已可使用，更新到PC的最新版：https://greasyfork.org/zh-CN/scripts/458024-v2next

请注意，如果你使用了手机版的脚本，也必须更新到最新版：https://greasyfork.org/zh-CN/scripts/485356，否则记事本数据会乱
