### ISSUE TITLE
添加用户标签弹窗被首页主题弹窗遮挡

### ISSUE THREAD

**Issue by leic4u** [zyronon/V2Next#77]
在首页使用弹框模式打开主题帖子时，点击添加用户标签，添加标签的弹框在主题帖子弹窗下一层，没有显示出来，我还以为没有显示，一直点一直点。关掉主题帖子弹框才发现有个添加标签的弹框在首页页面上。

期望添加用户标签的弹框置于顶层，不被主题帖子弹窗遮挡。

![image](https://github.com/zyronon/web-scripts/assets/32786903/907791ef-8317-43ad-be08-7eb609914169)

**Comment by zyronon** [comment]
谢谢，已修复，https://greasyfork.org/zh-CN/scripts/458024-v2next

此bug是昨天有个脚本作者让我兼容他的脚本导致的：https://github.com/zyronon/web-scripts/issues/72

**Comment by leic4u** [comment]
好的，谢谢，你又让我发现了一个好用的脚本😁
