### ISSUE TITLE
jq未载入报错的问题

### ISSUE THREAD

**Issue by JJins** [zyronon/V2Next#78]
## 控制台报错：

很久以来的遗留问题，个人测试用截图的方式可以等待jq载入完成再加载脚本的主要功能，因不熟悉项目结构，就不提pr了，作者看看是不是可以通过这种方式解决下

<img width="603" alt="图片" src="https://github.com/zyronon/web-scripts/assets/5475863/237a888a-746f-40c4-afb7-6ee9e66a1767">

**Comment by zyronon** [comment]
已添加jq依赖：https://greasyfork.org/zh-CN/scripts/458024
