### ISSUE TITLE
为何回复数量很多时就不能解析楼中楼了呢

### ISSUE THREAD

**Issue by LoneFireBlossom** [zyronon/V2Next#79]
> 由于回复数量较多，脚本已停止解析楼中楼

我有个习惯是遇到好帖子会保存下来，用SingleFile插件直接保存为离线网页。
正是因为有了这个脚本，我能把一个v2ex帖子的好几页回复合并到一页里，这样一次性就能保存所有回复。
而且用楼中楼的方式显示回复可读性高了很多。

今天发现回复数量较多（4页）的时候就停止解析了，是因为账号风险问题吗

**Comment by zyronon** [comment]
不是，代码做了限制。很多人反馈回复较多时会卡死，所以现在超过400条回复会停止解析

**Comment by LoneFireBlossom** [comment]
了解了，我倒还没有遇到过卡死的情况。超过400条回复的情况确实少之又少，很少需要。
当然如果以后能优化脚本性能就更好了😄
