### ISSUE TITLE
界面错位了

### ISSUE THREAD

**Issue by zlsq** [zyronon/V2Next#8]
https://www.v2ex.com/t/905252

<img width="823" alt="image" src="https://user-images.githubusercontent.com/17634558/233760322-50f08d4a-8af6-479d-abaf-5799a05b9f07.png">

**Comment by zyronon** [comment]
是不是自实义css了？或者用了其他插件

**Comment by zyronon** [comment]
![image](https://user-images.githubusercontent.com/19986642/233760735-4132f9ca-45cb-4e58-8f13-13a734ca7840.png)

**Comment by zlsq** [comment]
@zyronon  奇怪，我从首页进去就没事，通过url进去就这样

**Comment by coolzjy** [comment]
same issue，缩放设置为 150% 导致的。

**Comment by zyronon** [comment]
已修复，请更新到最新版本
