### ISSUE TITLE
`新标签页打开`时遇到的问题

### ISSUE THREAD

**Issue by wangbiye** [zyronon/V2Next#81]
Chrome 开启多个 Tab, V2EX 在中间, 此时开一个帖子打开新标签页, 关闭标签页的时候会跳到右边的 Tab, 但是 V2EX 是在左边, 每次都要多点一下

**Comment by zyronon** [comment]
和脚本没关系。这是浏览器规则

**Comment by wangbiye** [comment]
v2next/core/core.ts 中使用 GM_openInTab() 打开了一个新 Tab

**Comment by wangbiye** [comment]
是的, 我查看了一下代码, 在 v2next/core/core.ts 中使用 GM_openInTab() 打开了一个新 Tab, 我咨询 Gemini 确实是因为 Chrome 的默认行为造成的; 
不过我关闭脚本, 通过 CMD+点击的方式打开新 Tab, 然后手动切换过去, 再关掉, 是可以回到左侧 Tab 的, 所以我觉得可以优化脚本, 获得更好的体验, 我不太熟悉前端, 咨询了一下 Gemini: https://g.co/gemini/share/e3303011b38d

**Comment by zyronon** [comment]
我关闭脚本后，用 CMD+点击的方式新开了5个 Tab，然后我切换到5个Tab中间那个Tab，关闭之后，浏览器总是切换到右侧的Tab，直到右侧没有为止

**Comment by wangbiye** [comment]
https://github.com/zyronon/web-scripts/assets/9958811/6a60dc3c-941e-4950-96ae-2be32cadbf69

防止文字描述有歧义, 我录了一个视频;  关闭脚本之后, 从 V2EX 新开一个标签还是两个标签, 关闭之后都会回到 V2EX 的页面

**Comment by zyronon** [comment]
开了脚本也是这样啊

**Comment by zyronon** [comment]
知道了，这个问题我不知道怎么处理。。

**Comment by zyronon** [comment]
你Gemini 贴的回复里面，说active值啥啥啥的，那个值是控制是否马上切换的，设为true的话，新开的标签号，立马就会切换过去了
