### ISSUE TITLE
打开旧帖子不解析楼中楼信息

### ISSUE THREAD

**Issue by pockyneko** [zyronon/V2Next#82]
1.打开自己回复过的帖子的时候，script不解析楼中楼，点击页面上方的脚本设置也是打不开，完全没反应，
2.到首页打开新发的帖子又是可以解析楼中楼的
还有就是求问一下，你v2 号怎么没了，，

**Comment by zyronon** [comment]
已修复，https://greasyfork.org/zh-CN/scripts/458024-v2next

v2号被封了😅😅😅

**Comment by pockyneko** [comment]
> 已修复，https://greasyfork.org/zh-CN/scripts/458024-v2next
> 
> v2号被封了😅😅😅

感谢老哥，号被封也太惨了
