### ISSUE TITLE
iOS下卡在转圈刷新上，无法显示。

### ISSUE THREAD

**Issue by rongpengli** [zyronon/V2Next#83]
如图
![IMG_6013](https://github.com/zyronon/web-scripts/assets/10457822/0eb2ed6a-0b40-42fa-8059-16d0b8befed8)

**Comment by leic4u** [comment]
Android kiwi浏览器出现一样的情况

**Comment by zyronon** [comment]
已修复，https://greasyfork.org/zh-CN/scripts/485356

请注意脚本管理器是否开启自动更新，否则需要手动更新到最新版本
