### ISSUE TITLE
”弹框查看主题“功能，帖子错乱

### ISSUE THREAD

**Issue by betterwusy** [zyronon/V2Next#84]
## 问题：在 mac 上，使用”弹框查看主题“功能，点击标题后，弹框内容的帖子不是我点的那一个帖子。在 windows 上一切正常，没有这个bug
设备： macbookAir M1, 
浏览器：chrome, 版本 122.0.6261.112（正式版本） (arm64)
v2Next 版本：7.3
## 截图：
<img width="1568" alt="image" src="https://github.com/zyronon/web-scripts/assets/75969666/372572b8-618e-462c-8ba3-8f136338ccf1">
<img width="1903" alt="image" src="https://github.com/zyronon/web-scripts/assets/75969666/fe47ca93-2384-41c2-9af0-68477dbaa988">

**Comment by zyronon** [comment]
建议使用最新版本...

另外检测下是不是其他脚本导致的...

**Comment by zyronon** [comment]
你这个问题是贴子id超出1000000了，7.3版本只解析了6位id....
