### ISSUE TITLE
移动端脚本用户标签功能未成功工作

### ISSUE THREAD

**Issue by leic4u** [zyronon/V2Next#85]
## 问题：
看到移动端脚本设置中是有用户标签的开关选项的，但是实际上没有显示出来。

## 截图：
![image](https://github.com/zyronon/web-scripts/assets/32786903/03c1c2b5-22c2-4846-9eae-244094d6b0b6)
![image](https://github.com/zyronon/web-scripts/assets/32786903/0cf0709b-651b-453d-a4c4-ab8f97754baa)

**Comment by zyronon** [comment]
嗯，这个后面有空再弄

**Comment by starryspace** [comment]
+1，需要这个功能，盼修复

**Comment by zyronon** [comment]
App 已发布， @leic4u @starryspace 两位可以试试。

@starryspace 移动端脚本以后不会维护了

**Comment by leic4u** [comment]
> App 已发布， @leic4u @starryspace 两位可以试试。
> 
> @starryspace 移动端脚本以后不会维护了

完蛋。。。不是很想专门装个APP。。。我还是比较喜欢PWA和H5应用这种，用完即走，轻量一点。
