### ISSUE TITLE
v2ex mobile脚本加载不出旧帖子的楼中楼

### ISSUE THREAD

**Issue by LoneFireBlossom** [zyronon/V2Next#86]
## 问题：
如标题所说
iOS 17.3
Safari浏览器
stay脚本管理器
脚本是8.3

比如这个帖子
https://www.v2ex.com/t/938037?p=2

## 截图：
![IMG_2042](https://github.com/zyronon/web-scripts/assets/50087596/b013ff9b-b6e7-4b33-a73a-aa904a103310)

**Comment by zyronon** [comment]
发现有标签的帖子会出现评论无法加载的情况

现在已修复，https://greasyfork.org/zh-CN/scripts/485356

请注意脚本管理器是否开启自动更新，否则需要手动更新到最新版本
