### ISSUE TITLE
9.5更新了什么吗，突然发现不能和小鱼标签一起用了

### ISSUE THREAD

**Issue by wk333** [zyronon/V2Next#88]
## 问题：
和小鱼标签 一起使用会导致脚本失效，无法打开弹窗
https://greasyfork.org/zh-CN/scripts/460718-utags-add-usertags-to-links

**Comment by AlexZhong22c** [comment]
和小鱼标签 一起使用 会导致脚本没有“楼中楼” https://v2ex.com/t/1030787

**Comment by zyronon** [comment]
好的，正在处理中...

**Comment by zyronon** [comment]
@AlexZhong22c @wk333 已修复
