### ISSUE TITLE
「主题宽度」只在窗口最大化时有效，窗口宽度大约小于 1500px 无效

### ISSUE THREAD

**Issue by hiforrest** [zyronon/V2Next#90]
## 问题：
「主题宽度」只在窗口最大化时有效，窗口宽度大约小于 1500px 无效

## 截图：
设置主题宽度：
![SP_2024-03-31_14-22-55](https://github.com/zyronon/web-scripts/assets/2953848/760cda8a-6386-44fe-8a02-690228a19e00)

最大化窗口：
![SP_2024-03-31_14-26-04](https://github.com/zyronon/web-scripts/assets/2953848/ee5cb97f-5d50-48cc-b7c9-4eb76fbbdd11)

窗口小于1500px：
![SP_2024-03-31_14-23-14](https://github.com/zyronon/web-scripts/assets/2953848/2c75ba49-dbff-4265-a8b1-7ec571610004)

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
已在10.3版本修复，请更新
