### ISSUE TITLE
功能建议：base64 划词 建议选中全是英文或者以英文开始才显示

### ISSUE THREAD

**Issue by yangg** [zyronon/V2Next#91]
## 问题：
主要是现在选中文啥的也显示，感觉没必要

**Comment by zyronon** [comment]
有判断，不会乱显示的

**Comment by yangg** [comment]
<img width="802" alt="image" src="https://github.com/zyronon/web-scripts/assets/409225/aed7306e-7cd2-4ef7-bee1-2be8e99ab193">
