### ISSUE TITLE
v2next的[高赞回复]里面的[回复]在夜间模式下字体颜色为黑色很难看清

### ISSUE THREAD

**Issue by zhufeng** [zyronon/V2Next#93]
## 问题：
v2next的 [高赞回复] 里面的 [回复] 在  夜间模式  下  字体颜色   为  黑色   很难看清

## 截图：
![QQ截图20240411110537](https://github.com/zyronon/web-scripts/assets/1539043/a4837493-b8ac-4854-9207-48a3dbe15231)

## 控制台报错：
无

**Comment by zhufeng** [comment]
补充，版本为 v10.1。

**Comment by zyronon** [comment]
已修复。需更新到10.2
