### ISSUE TITLE
夜间模式下主题弹框背景仍为白天的灰色

### ISSUE THREAD

**Issue by Huchikoma** [zyronon/V2Next#94]
## 问题：
夜间模式下主题弹框背景仍为白天的灰色，之前不会有这个问题，应该是近一周的更新导致。
## 截图：
<img width="1418" alt="image" src="https://github.com/zyronon/web-scripts/assets/45927072/f4efcec5-fa2e-4a54-a967-28ac79702c4f">

**Comment by zyronon** [comment]
无法复现
