### ISSUE TITLE
偶发楼层对应错误

### ISSUE THREAD

**Issue by CharlesTHN** [zyronon/V2Next#95]
## 问题：
楼层对应错误
## 截图：
![image](https://github.com/zyronon/web-scripts/assets/19632429/c6f2f30b-6803-4d69-bfd0-ac721e02a795)
![image](https://github.com/zyronon/web-scripts/assets/19632429/e63241fb-ffd7-425a-b631-11ee31de4ecd)

**Comment by zyronon** [comment]
好的，1031562

**Comment by zyronon** [comment]
你框的这个条回复，楼层符写成1#了，那样是不会被识别到的。正确的作法应该是 #1

就像下面的这条回复一样
![image](https://github.com/zyronon/web-scripts/assets/19986642/fad6c844-7c82-487d-8e27-4cba9085d8d1)
