### ISSUE TITLE
插件会把append功能隐藏掉，导致发帖人无法append主贴内容

### ISSUE THREAD

**Issue by vagrant2046** [zyronon/V2Next#97]
1、是否在关闭其他插件和脚本后复现？

是

2、描述

插件会把append功能隐藏掉，导致发帖人无法append主贴内容

3、帖子ID
无需帖子id，需要发帖人自己复现，v2机制是发布一个主贴后一定的回复数量后OP可以append主贴

4、截图

![11111](https://github.com/zyronon/web-scripts/assets/5989014/e029aa1c-5080-43de-b42b-ba8975de22ae)

**Comment by zyronon** [comment]
啥版本？还在用7.8？

这个bug我早就修复了啊

**Comment by vagrant2046** [comment]
> 啥版本？还在用7.8？
> 
> 这个bug我早就修复了啊

不好意思，更新到最新版本解决了。感谢
