### ISSUE TITLE
问题报告：Safari on macOS 14.5 上无法使用“在新标签页打开链接”

### ISSUE THREAD

**Issue by A1aM0** [zyronon/V2Next#99]
1、是否在关闭其他插件和脚本后复现？

可以复现

2、描述

我的浏览器是Safari，macOS 14.5，script 版本是 10.2，使用的插件是 UserScrpts
如下面截图所示，设置为“新标签页打开链接”，点击任一个帖子都没有反应

“弹窗显示”或者关闭“新标签页打开”则可以正常使用

3、帖子ID
<无>

4、截图
<img width="644" alt="image" src="https://github.com/zyronon/web-scripts/assets/39716458/743ebfee-19e0-40ea-8b1d-5c2a95ecdbd6">

**Comment by A1aM0** [comment]
<img width="813" alt="image" src="https://github.com/zyronon/web-scripts/assets/39716458/2fa3fc3c-f45f-4119-8b90-15cfcba9394a">
补充一下console的输出

**Comment by zyronon** [comment]
收到

**Comment by zyronon** [comment]
已在10.3版本修复，请更新
